### ISSUE TITLE
Base Switch @click not working

### ISSUE THREAD

**Issue by modulati0ns** [creativetimofficial/nuxt-black-dashboard#2]
Hi!

I'm making a web using this wonderful template with Nuxt.js. I'm trying to make a BaseSwitch work. It gets imported fine into my nuxt page, and renders and works perfectly using v-model. (Using :value get stuck, but i guess it is because i'm not changing its value (living in the data of the page of nuxt) in any method). The thing is I want to change the value using a method, and calliing it using something like:

```
<base-switch
    :value="status"
    @click="updateStatus()"
 ></base-switch>

```

And in the updateStatus() method do something like.

```
updateStatus(){
       this.status = !this.status
}
```

The thing is that I cant make the  @click think to work. Neither @change. 

Sorry if this question is too basic and I'm missing something obvious in the way.

Thank you!

**Comment by lesnah27** [comment]
Hola resolviste?
