### ISSUE TITLE
deps

### ISSUE THREAD

**Issue by rafalohaki** [creativetimofficial/nuxt-black-dashboard#5]
seems like deps are too old and deprecated and upgrading breaks a code and doesnt work from installing

**Comment by skyark21** [comment]
Hi, I modify the package.json file and it works for me.

```
{
  "name": "nuxt-black-dashboard",
  "version": "1.0.0",
  "description": "Nuxt Black Dashboard",
  "author": "creativetim",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@nuxtjs/pwa": "^3.0.0-beta.16",
    "bootstrap": "4.3.1",
    "chart.js": "^2.7.1",
    "d3": "^5.7.0",
    "element-ui": "^2.11.1",
    "es6-promise": "^4.1.1",
    "fuse.js": "^3.2.0",
    "google-maps": "^3.2.1",
    "nuxt": "^2.15.8",
    "nuxt-i18n": "^6.28.1",
    "perfect-scrollbar": "^1.3.0",
    "register-service-worker": "^1.5.2",
    "tween.js": "^16.6.0",
    "vue": "^2.7.8",
    "vue-chartjs": "^3.4.0",
    "vue-i18n": "^8.26.1",
    "vue-server-renderer": "^2.7.8",
    "vue2-transitions": "^0.2.3",
    "vue-template-compiler": "^2.7.8"
  },
  "devDependencies": {
    "babel-plugin-component": "^1.1.1",
    "node-sass": "^6.0.1",
    "sass-loader": "^10.2.1"
  }
}
```

Hope it works out for you too.

**Comment by rafalohaki** [comment]
> {
>   "name": "nuxt-black-dashboard",
>   "version": "1.0.0",
>   "description": "Nuxt Black Dashboard",
>   "author": "creativetim",
>   "private": true,
>   "scripts": {
>     "dev": "nuxt",
>     "build": "nuxt build",
>     "start": "nuxt start",
>     "generate": "nuxt generate"
>   },
>   "dependencies": {
>     "@nuxtjs/pwa": "^3.0.0-beta.16",
>     "bootstrap": "4.3.1",
>     "chart.js": "^2.7.1",
>     "d3": "^5.7.0",
>     "element-ui": "^2.11.1",
>     "es6-promise": "^4.1.1",
>     "fuse.js": "^3.2.0",
>     "google-maps": "^3.2.1",
>     "nuxt": "^2.15.8",
>     "nuxt-i18n": "^6.28.1",
>     "perfect-scrollbar": "^1.3.0",
>     "register-service-worker": "^1.5.2",
>     "tween.js": "^16.6.0",
>     "vue": "^2.7.8",
>     "vue-chartjs": "^3.4.0",
>     "vue-i18n": "^8.26.1",
>     "vue-server-renderer": "^2.7.8",
>     "vue2-transitions": "^0.2.3",
>     "vue-template-compiler": "^2.7.8"
>   },
>   "devDependencies": {
>     "babel-plugin-component": "^1.1.1",
>     "node-sass": "^6.0.1",
>     "sass-loader": "^10.2.1"
>   }
> }

works like a charm, thank you!
